import Head from 'next/head'
import Sidebar from '../components/Sidebar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create chat-app</title>
        <meta name="description" content="Generated by Tu" />
      </Head>
      <Sidebar />
    </div>
  )
}
